"""Add parcela_group_id

Revision ID: 928f8d21ff66
Revises: 6ebfbfe82b99
Create Date: 2026-02-24 02:47:04.255043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928f8d21ff66'
down_revision: Union[str, None] = '6ebfbfe82b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lancamentos', sa.Column('parcela_group_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_lancamentos_parcela_group_id'), 'lancamentos', ['parcela_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lancamentos_parcela_group_id'), table_name='lancamentos')
    op.drop_column('lancamentos', 'parcela_group_id')
    # ### end Alembic commands ###
