"""Add user_id to categoria

Revision ID: cc4034f496ee
Revises: 928f8d21ff66
Create Date: 2026-02-24 13:52:49.168663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4034f496ee'
down_revision: Union[str, None] = '928f8d21ff66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categorias', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categorias', type_='foreignkey')
    op.drop_column('categorias', 'user_id')
    # ### end Alembic commands ###
